# This file was generated by GoReleaser. DO NOT EDIT.
class PlantumlEncode < Formula
  desc "Encodes PlantUML source to send to the server."
  homepage ""
  version "0.12.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/orlade/plantuml-encode/releases/download/v0.12.0/plantuml-encode_0.12.0_darwin-amd64.tar.gz"
    sha256 "6a1795863e550242c2a564f179c3666b5c6d25af408f1423e390cc63c00659e5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/orlade/plantuml-encode/releases/download/v0.12.0/plantuml-encode_0.12.0_linux-amd64.tar.gz"
      sha256 "723113f09f42eef33b6a263ebb188d53fd7499bebe3e7b3433f69b4b558b308b"
    end
  end

  def install
    bin.install "plantuml-encode"
  end

  test do
    system "#{bin}/plantuml-encode --version"
  end
end
